name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Dodaj swój krok budujący stronę, np.:
      # - run: npm install && npm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./public # lub inny folder z plikami strony
